### ISSUE TITLE
( JIRA #1 ) No System Timeout

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#404]
In testing timeout application was left idle for more than 10 hours (overnight) upon return the user session did not expire and the user was able to continue working on the site.

**Comment by leobardoramon** [comment]
Can we do a server-side timeout?

**Comment by NYU-AMS** [comment]
let see is Barry has any ideas on how to do this.

**Comment by barryross** [comment]
The sessions are handled through express, correct? `js/session.js` ?

**Comment by gosha1128** [comment]
Yes...and due to legacy reasons the session state is serialized to a file
in /amsfiles/sessions

**Comment by barryross** [comment]
Thanks for the clarification George....what if we incorporate a `previousRequest` timestamp to the .json file.   Every time the user navigated to a new page, and `handle_get_session()` is called from `api/session.js` we  a) check to see if the   `lastrequest` timestamp is within the appropriate idle time window (which we set).  If it is beyond, we log the user out, otherwise we add a `lastrequest` timestamp to the .json file and process the user's request?

**Comment by gosha1128** [comment]
Great, that works !

-g

**Comment by barryross** [comment]
Great!

**Comment by barryross** [comment]
@leobardoramon @gosha1128 what idle time do we want to use for this?

**Comment by barryross** [comment]
Believe I have resolved this, and currently sets idle time to 1hour limit.  

Please test on `contractor_barry`
Relevant Commit: https://github.com/codetodesign/NYUAMS/commit/0263d00448c29c1cb9d17a97dbf70ce9a5804787

**Comment by buck0land** [comment]
Let's say half hour for now

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On Feb 3, 2017, at 4:50 PM, Barry Ross <notifications@github.com> wrote:

Believe I have resolved this, and currently sets idle time to 1hour limit.

Please test on contractor_barry
Relevant Commit: 0263d00
<https://github.com/codetodesign/NYUAMS/commit/0263d00448c29c1cb9d17a97dbf70ce9a5804787>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codetodesign/NYUAMS/issues/404#issuecomment-277371723>,
or mute the thread

**Comment by barryross** [comment]
@buck0land  sounds great, thanks Andrew
