### ISSUE TITLE
Test Case:  File Upload - no cancel button

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#496]
No way of canceling file upload

Workaround:  Must refresh browser window to cancel file upload

**Comment by barryross** [comment]
To clarify....Is the problem that the user may want to remain in the wizard but remove a file they just uploaded?  Otherwise, they could click the "x" to close, without refreshing.  So we need a trash can icon or something next to each uploaded file name? 

<img width="452" alt="screen shot 2016-12-09 at 12 11 45 pm" src="https://cloud.githubusercontent.com/assets/2281667/21063058/94ceacc8-be08-11e6-813b-666705de6e67.png">

**Comment by leobardoramon** [comment]
so the idea of this is, once issue #533 has been implemented, the user will have a way to get out of this panel without wait for the upload to complete

**Comment by barryross** [comment]
Oh, so the "cancel" button would be present before, during, and after file upload?  And during the file upload, it should be the only "unlocked" portion of the wizard?

**Comment by leobardoramon** [comment]
perfect

**Comment by barryross** [comment]
okay, glad to hear

**Comment by barryross** [comment]
After taking another look, If I simply disable "back" and "next" for #533 , wouldn't the "x" in the top-right achieve the functionality described above?  Note in the video, if I click "x" before the upload completes, the new file is not listed in the window when I open it again.

**Comment by leobardoramon** [comment]
The problem in this scenario is that the file is still being uploaded in the background ( even if the "x" is selected ) and if the file upload is causing issues with the server, the server performance will still be affected .  Does this make sense, @barryross ?

**Comment by barryross** [comment]
@leobardoramon Yes, I think so....so the "x" does need to be disabled during upload and the cancel would then stop the file transfer.  Makes sense.  Thanks!

**Comment by barryross** [comment]
Okay, so I'm gotten an implementation of this to work for New Orders, in the File Upload portion.  I've solved it by allowing the upload to continue, but on the callback, it removes the association with the current project the new order is for.  Does this work as a solution? 

I should have asked this sooner, but I wasn't as clear on how the various file upload mechanisms were working, and where.  Was this issue intended to be for New Orders, as well as adding files to existing projects and files to parts?  Or would that be a separate issue(s) scope? 

Relevant Commit: https://github.com/codetodesign/NYUAMS/commit/e242c304533f6c16dcfad94eb5d74e5e1ccf508e
Video Demo:
https://www.dropbox.com/s/mfz0agixs84goh2/496-file-cancel.mov?dl=0

**Comment by gosha1128** [comment]
Yes thats a good work around for now.

We should revisit this maybe as a different issue- this is because a large
canceled workload is still using the network until it's finished.  This
might cause an issue for a subsequent upload.

**Comment by barryross** [comment]
Okay, gotcha.  I played with the cancelUpload() method of the YUI library a bit, which may be helpful in terms of the server resources issue.  One thing I was running into with that was that that images actually upload rather quickly often, so I figured users would often actually click “cancel” after the uploaded completed…I suppose a more thorough solution would cover both cases.

How about I implement this current solution for the parts - > add file and the projects - > add file, and then open a new issue for expanding on all three of those to cancel the server in the process?  Or was that the scope of the initial task you were expecting? 

Thanks,
Barry

**Comment by gosha1128** [comment]
Perfect. Open the issue and Leo will prioritize for a later batch.

**Comment by barryross** [comment]
I realize you responded to my first suggestion, which works for me :)  I'll go ahead and restore it above.  Sounds like a plan, thanks!

**Comment by barryross** [comment]
Okay, so an update for this one.   I have updated it so the if you press cancel while the file is still uploading, once it uploads, it is removed from the system.  

The first video shows this working for the following, by interacting with UI and seeing associated DB changes
 a) Orders -> New Order,
 b) Projects -> add file, 
 c) Orders -> Parts -> Files - > Add File

https://www.dropbox.com/s/nyrskvdydzp6x1d/496-potential-issue.mov?dl=0

As part of my solution for this, I have it set so that if you have the panel open, you successfully upload file #1, then start uploading file #2, and press cancel before it is complete, both files #1 and files #2 are removed.  This is visible in the following video.  Can somebody please let me know if this is the functionality that you would like?  

https://www.dropbox.com/s/tdjkw7zo8lwy0hl/496-file-cancel-round2.mov?dl=0

thanks!

**Comment by leobardoramon** [comment]
This looks good to me.  @buck0land , what are your thoughts?

**Comment by buck0land** [comment]
Looks good to me.

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On Feb 7, 2017, at 4:34 PM, leobardoramon <notifications@github.com> wrote:

Assigned #496 <https://github.com/codetodesign/NYUAMS/issues/496> to
@buck0land <https://github.com/buck0land>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codetodesign/NYUAMS/issues/496#event-952853300>, or mute
the thread

**Comment by barryross** [comment]
@leobardoramon  @buck0land  thanks guys!

**Comment by leobardoramon** [comment]
@barryross Nice work!  

can we also add this to
 -  Orders > part(s) > Add Part

**Comment by barryross** [comment]
@leobardoramon Thanks!  Yup, I've gone ahead and added that for Orders > Part(s) > Add Part as well!

Relevant commit: https://github.com/codetodesign/NYUAMS/commit/3fc3eea26e33a690e700758482a48671349be13b

Video: 
https://www.dropbox.com/s/0w7pcvia2iawtbr/496-file-cancel-round3.mov?dl=0

**Comment by leobardoramon** [comment]
Looks good.

**Comment by barryross** [comment]
@leobardoramon great, thanks!
