### ISSUE TITLE
Test Case: Orders>New Order>panel6 - Layout/Formatting

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#503]
Quantity Field
![orders new panel6 qty](https://cloud.githubusercontent.com/assets/2165796/8169707/468f2c80-1379-11e5-9a85-0446a367a109.png)

**Comment by gosha1128** [comment]
low effort

**Comment by barryross** [comment]
Is the decision to have "Qty" default to "1" ?

**Comment by buck0land** [comment]
Yes Qty should default to 1.

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On Dec 9, 2016, at 2:59 PM, Barry Ross <notifications@github.com> wrote:

Is the decision to have "Qty" default to "1" ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codetodesign/NYUAMS/issues/503#issuecomment-266108441>,
or mute the thread

**Comment by barryross** [comment]
Roger that, thanks

**Comment by barryross** [comment]
Updated on `contractor_barry`, please test

<img width="772" alt="screen shot 2016-12-18 at 5 43 43 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298809/3b9c297a-c54a-11e6-8abc-407ee667f90d.png">
<img width="922" alt="screen shot 2016-12-18 at 5 46 02 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298810/3b9de508-c54a-11e6-831b-f3b797dc3497.png">
<img width="915" alt="screen shot 2016-12-18 at 5 47 09 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298811/3ba2f6ba-c54a-11e6-9151-0bb20b3e2814.png">

**Comment by barryross** [comment]
I see now I need to do this for each device

**Comment by barryross** [comment]
<img width="717" alt="screen shot 2017-01-08 at 10 24 37 pm" src="https://cloud.githubusercontent.com/assets/2281667/21758526/908a1cdc-d5f1-11e6-92b0-5e5495f6f37f.png">
<img width="625" alt="screen shot 2017-01-08 at 10 28 05 pm" src="https://cloud.githubusercontent.com/assets/2281667/21758527/909ce6aa-d5f1-11e6-8cb3-ae922467d129.png">

**Comment by leobardoramon** [comment]
Looks good.

**Comment by barryross** [comment]
glad to hear!
