### ISSUE TITLE
Test Case:  Orders>Checkout ( Credit Card )> "Authorization Code"

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#518]
Change "Authorization Code" to the actual wording that reads on the credit card receipt.
![screen shot 2015-07-20 at 4 24 18 pm copy](https://cloud.githubusercontent.com/assets/2165796/8786498/786a5394-2efc-11e5-8aca-46ca1b43095f.png)

**Comment by leobardoramon** [comment]
What is the term used on the receipt from the credit card machine?

**Comment by gosha1128** [comment]
not sure, check with ams?

**Comment by leobardoramon** [comment]
leo ask andrew to give you this

**Comment by barryross** [comment]
Hey Leo, did we find out what wording should be used here?

**Comment by NYU-AMS** [comment]
It should say "Approval Code"

Andrew Buckland
Technical lead, LaGuardia Studio (LGS)
Senior Advanced Media Specialist
Academic Technology Services, IT


New York University
545 Laguardia Place <x-apple-data-detectors://9/1>
New York, New York 10012 <x-apple-data-detectors://9/1>


Phone:(212)998-3610
email: andrew.buckland@nyu.edu

On Dec 16, 2016, at 4:16 PM, Barry Ross <notifications@github.com> wrote:

Hey Leo, did we find out what wording should be used here?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/codetodesign/NYUAMS/issues/518#issuecomment-267697871>,
or mute the thread

**Comment by barryross** [comment]
Thank you

**Comment by barryross** [comment]
Issue resolved, please test on `contractor_barry`
<img width="650" alt="screen shot 2016-12-16 at 1 39 25 pm" src="https://cloud.githubusercontent.com/assets/2281667/21279571/aeaa92f0-c395-11e6-8fcb-aa61d995f150.png">

**Comment by leobardoramon** [comment]
Looks good.
