### ISSUE TITLE
Test Case:  QUEUE page/main table - "file name" column populates properly

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#649]
Only the most recently uploaded file should appear in the "file name" field of the Queue table

- APPROVED -

See wireframe:
<img width="2088" alt="screen shot 2016-11-03 at 7 36 44 pm" src="https://cloud.githubusercontent.com/assets/2165796/19989809/6da764f2-a1ff-11e6-9e4c-80308c2fc8ef.png">

**Comment by barryross** [comment]
Please verify fix on "contractor_barry" branch

**Comment by leobardoramon** [comment]
This currently requires a refresh to update the file name...

is there a way to have the table data update without a refresh from the user?

**Comment by barryross** [comment]
A more user-friendly way may be to use jQuery/Ajax, but the simplest solution would probably just be to trigger a page refresh automatically after a new file is uploaded...the former option may be better suited as a separate function that could be re-used throughout the codebase if this issue comes up a lot.  I"ll have a better idea after I review the specific code.

**Comment by leobardoramon** [comment]
...one thing that we should note is that since the table is located within a "subtab" , a refresh causes the page to go back to "the beginning"

Does this make sense?  would either of your suggested solutions still provide a fix in light of this information?

**Comment by barryross** [comment]
It makes total sense...I think the way to do it may be when the user clicks "done" after replacing the image...the system should detect which subtab has been clicked and emulate another click on it....see video below

**Comment by barryross** [comment]
https://www.dropbox.com/s/tg2hd8z7kc8vven/file_refresh.mov?dl=0

**Comment by leobardoramon** [comment]
yes, this looks good to me.  Please proceed

**Comment by barryross** [comment]
Okay, will do...I will plan on moving forward on this tomorrow

**Comment by barryross** [comment]
Okay, it looks like I came up with a solution for this.  Moving forward, I'd like to leverage promises in the front-end, but I didn't see a promise library currently being leveraged outside of the db and api, so I held off for now in order to move forward on this...as it turned out to be a bit of a tricky improvement. 

Leo, I did want to check with you to see if you are aware of any other locations outside of the queue/replace feature, for which having added the following callback on line #373 of `upload_files_manager.js`may be an issue? 

Please test on "contractor_barry" branch


![image](https://cloud.githubusercontent.com/assets/2281667/21157759/74326570-c12f-11e6-9bd7-169af9f9b000.png)

**Comment by gosha1128** [comment]
Yes go ahead with promise deferred in the front end.

**Comment by barryross** [comment]
Sorry for the delayed response @gosha1128 , thanks for the confirmation with the promise deferred in front end - will be working on this today

**Comment by barryross** [comment]
@gosha1128 Any problem with me using YUI's promise library even though it looks like YUI is no longer maintained?  Seems like it would fit in with the current setup nicely though.

**Comment by gosha1128** [comment]
No problem.  Feel free to move away from YUI...I've been concerned about
YUI support going forward...

**Comment by barryross** [comment]
Okay, sounds good…I was playing around with the YUI promises earlier, and will look into incorporating a more up-to-date library.

**Comment by barryross** [comment]
Okay, incorporated the "q" promise library on the front-end.  Believe this is now resolved.  Please see video and check on `contractor_barry`

https://www.dropbox.com/s/b9ful2wxhusny3i/promise-refresh-queue.mov?dl=0

**Comment by leobardoramon** [comment]
It takes a few seconds ( ~ 7 - 12 seconds ) but I'm happy with it.  Looks good

**Comment by barryross** [comment]
@leobardoramon  Just noticed that this is causing an issue when adding files through `orders` or `projects`.  

<img width="1061" alt="screen shot 2017-03-02 at 12 34 29 pm" src="https://cloud.githubusercontent.com/assets/2281667/23526931/c297863a-ff48-11e6-9034-4dfb69a9f378.png">

**Comment by barryross** [comment]
@leobardoramon  

I have gone ahead and added a patch, available on `contractor_barry` which appears to have resolved the issue.  Would you like me to merge this to `master` asap?
